/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    ComControls: typeof import('./src/components/ComControls.vue')['default']
    ComControlsErrors: typeof import('./src/components/ComControlsErrors.vue')['default']
    ComForm: typeof import('./src/components/ComForm/ComForm.vue')['default']
    ComFormErrors: typeof import('./src/components/ComForm/ComFormErrors.vue')['default']
    ComNavbar: typeof import('./src/components/ComNavbar.vue')['default']
    ComRouteTreeNode: typeof import('./src/components/ComRouteTreeNode.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    Form: typeof import('@primevue/forms/form')['default']
    FormField: typeof import('@primevue/forms/formfield')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    Panel: typeof import('primevue/panel')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RouteTreeNode: typeof import('./src/components/RouteTreeNode.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
  }
}
