/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable

import { createSSRApp } from 'vue'
import { createPinia } from 'pinia'
// import { createAppPinia } from './stores'
import App from './App.vue'
import router from './router'
// import PrimeVue from 'primevue/config';
// import ToastService from 'primevue/toastservice';
// import { definePreset } from '@primeuix/themes';
// import Aura from '@primeuix/themes/aura';

// const MyPreset = definePreset(Aura, {
//   semantic: {
//     primary: {
//       50: '{sky.50}',
//       100: '{sky.100}',
//       200: '{sky.200}',
//       300: '{sky.300}',
//       400: '{sky.400}',
//       500: '{sky.500}',
//       600: '{sky.600}',
//       700: '{sky.700}',
//       800: '{sky.800}',
//       900: '{sky.900}',
//       950: '{sky.950}',
//     },
//   },
// });

export function createApp() {
  const app = createSSRApp(App)
  const pinia = createPinia()

  // app.use(PrimeVue, {
  //   theme: {
  //     preset: MyPreset,
  //     options: {
  //       darkModeSelector: '.p-dark',
  //       cssLayer: false,
  //     },
  //   },
  // });

  // Retrieve and hydrate Pinia state
  if (typeof window !== 'undefined' && window.__PINIA_STATE__) {
      pinia.state.value = window.__PINIA_STATE__;
  }

  app.use(router)
  app.use(pinia)
  // app.use(ToastService)

  return { app, router, pinia }
}
